---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: hello
  namespace: flux-system
spec:
  interval: 1m 
  ref:
    branch: main 
  url: https://github.com/ks-yim/fluxcd-playground
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/

