apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: world 
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/hello
      sourceRef:
        kind: GitRepository
        name: hello
  interval: 1m0s
  targetNamespace: default
  values:
    image:
      tag: 0.1.2

