---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: hello
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello
  policy:
    semver:
      range: 0.1.x

