---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
  namespace: default
spec:
  chart:
    spec:
      chart: hello
      sourceRef:
        kind: GitRepository
        name: hello
        namespace: flux-system
  interval: 1m0s

